### PR TITLE
Update EAP version.

### PR DESCRIPTION
**Pull request by AraHaan**

### CODE REVIEW

**Comment by ForNeVeR** [comment]
I don't think this is required at all. The plugin version built for EAP4 should already be compatible with any newer EAP versions.

**Comment by AraHaan** [comment]
I do not think so, currently in rider it says whatever version it says now that it is compatible with that version or older.

**Comment by ForNeVeR** [comment]
Probably because the updated version wasn't yet deployed.

**Comment by matkoch** [comment]
See https://github.com/controlflow/resharper-heapview/issues/82

**Pull request closed without merging**
